# Default initial positions for fr3v2's ros2_control fake system

initial_positions:
  fr3v2_finger_joint1: 0
  fr3v2_joint1: 0
  fr3v2_joint2: 0
  fr3v2_joint3: 0
  fr3v2_joint4: -1.5
  fr3v2_joint5: 0
  fr3v2_joint6: 1.0
  fr3v2_joint7: 0
