# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - fr3v2_joint1
      - fr3v2_joint2
      - fr3v2_joint3
      - fr3v2_joint4
      - fr3v2_joint5
      - fr3v2_joint6
      - fr3v2_joint7
    action_ns: follow_joint_trajectory
  gripper_controller:
    type: GripperCommand
    joints:
      - fr3v2_finger_joint1
    action_ns: gripper_cmd
    default: true
